version: "3.7"

services:     
    api:  
     container_name: fastapi
     build: .
     ports: 
      - 80:80
      - 8080:8080
    
# version: '3.7'

# services:
#   api:
#     container_name: fastapi_demo
#     build: .
#     ports:
#       - 80:80